### ISSUE TITLE
Error when importing Postman.json

### ISSUE THREAD

**Issue by Drilio** [EsperoTech/yaade#171] opened 2024-07-08 09:48 UTC
Hello,

I want to switch from postman to Yaade. I need to import my set-up into yaade

- I exported my postman set-up using Collection v2 and v2.1
- I use 'create  a new collection' in Yaade
-  switch to import 
- select 'Postman'
- choose the right file
- click 'Create'

And I have this error : 'The collection could be not created'

I can give you the two json output from Postman if it help.

**Comment by Drilio** [comment] 2024-07-08 13:09
I have this message into console :

**Comment by Drilio** [comment] 2024-07-08 13:11
I have an error 500 with this message  :
```
```

**Comment by shafamail** [comment] 2024-07-24 05:31
I have the same error:

Shows `TypeError: Failed to construct 'URL': Invalid URL` in the browser console.

It fails for both Postman and OpenAPI collection import (Local and Sever behind NginX on default base path)

**Comment by paulo-hortelan** [comment] 2024-07-30 20:23
I'm having the same problem, any news on the issue?

**Comment by jonrosner** [comment] 2024-07-31 09:08
This is next on my list. I looked at it briefly and looks like Postman has a few different formats that are not considered yet.

**Comment by jonrosner** [comment] 2024-08-01 21:35
I merged a fix to this problem. Please fetch the latest docker container and see if it resolved your problem.

**Comment by progsoftpack** [comment] 2024-08-02 09:34
I also have problems importing from postman (v2 and v2.1)
It gives "The collection cannot be created"
And the log:
```bash
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.url
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:53)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:24)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemGroupDeserializer.deserialize(ItemGroupDeserializer.java:44)
at com.postman.collection.adapter.ItemGroupDeserializer.deserialize(ItemGroupDeserializer.java:19)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:43)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:24)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1262)
at com.google.gson.Gson.fromJson(Gson.java:1171)
at com.google.gson.Gson.fromJson(Gson.java:1107)
at com.postman.collection.Collection.pmcFactory(Collection.java:438)
at com.espero.yaade.services.PostmanParser.parseCollection(PostmanParser.kt:22)
at com.espero.yaade.server.routes.CollectionRoute.importPostmanCollection(CollectionRoute.kt:289)
at com.espero.yaade.server.routes.CollectionRoute$importPostmanCollection$1.invokeSuspend(CollectionRoute.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:144)
at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:143)
at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.url
at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:179)
at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:96)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509)
... 61 more
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.url
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:520)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:53)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:24)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemGroupDeserializer.deserialize(ItemGroupDeserializer.java:44)
at com.postman.collection.adapter.ItemGroupDeserializer.deserialize(ItemGroupDeserializer.java:19)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1463)
at com.google.gson.Gson.fromJson(Gson.java:1434)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:199)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:43)
at com.postman.collection.adapter.ItemDeserializer.deserialize(ItemDeserializer.java:24)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:95)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:83)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:59)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$2.readIntoField(ReflectiveTypeAdapterFactory.java:267)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:558)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:516)
at com.google.gson.Gson.fromJson(Gson.java:1361)
at com.google.gson.Gson.fromJson(Gson.java:1262)
at com.google.gson.Gson.fromJson(Gson.java:1171)
at com.google.gson.Gson.fromJson(Gson.java:1107)
at com.postman.collection.Collection.pmcFactory(Collection.java:438)
at com.espero.yaade.services.PostmanParser.parseCollection(PostmanParser.kt:22)
at com.espero.yaade.server.routes.CollectionRoute.importPostmanCollection(CollectionRoute.kt:289)
at com.espero.yaade.server.routes.CollectionRoute$importPostmanCollection$1.invokeSuspend(CollectionRoute.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:144)
at io.vertx.kotlin.coroutines.VertxCoroutineKt$coAwait$2$1.handle(VertxCoroutine.kt:143)
at io.vertx.core.impl.future.FutureImpl$4.onSuccess(FutureImpl.java:176)
at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:60)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $.url
at com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:179)
at com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:96)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:509)
... 61 more
```

**Comment by jonrosner** [comment] 2024-08-02 10:06
@progsoftpack are you already using the latest docker container I released yesterday? If so, can you share a minimal reproducible example?

**Comment by progsoftpack** [comment] 2024-08-02 17:37
I'm using that docker image: esperotech/yaade:latest
There is an example:
```json
{
	"info": {
		"_postman_id": "81d29962-3178-4f92-99e0-af4071ab0c9d",
		"name": "My collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json",
		"_exporter_id": "27307316"
	},
	"item": [
		{
			"name": "Login Copy",
			"item": [
				{
					"name": "Login",
					"event": [
						{
							"listen": "test",
							"script": {
								"exec": [
									"var jsonData = pm.response.json();",
									"const token = jsonData.data.token;",
									"pm.collectionVariables.set('token', token);"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"auth": {
							"type": "noauth"
						},
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"username\": \"administrador\",\n    \"password\": \"administrador\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": "{{endereco}}/api/auth/login",
						"description": "Permite fazer o login para utilizar a maioria dos endpoints desta Api.  \n\nEste pedido devolve um token que deve ser incluido na maioria dos pedidos a esta Api."
					},
					"response": [
						{
							"name": "Login",
							"originalRequest": {
								"method": "POST",
								"header": [],
								"body": {
									"mode": "raw",
									"raw": "{\n    \"username\": \"teste\",\n    \"password\": \"teste\"\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{endereco}}/api/login",
									"host": [
										"{{endereco}}"
									],
									"path": [
										"api",
										"login"
									],
									"query": [
										{
											"key": "username",
											"value": "ola",
											"disabled": true
										},
										{
											"key": "password",
											"value": "joaquim",
											"disabled": true
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Date",
									"value": "Fri, 22 Jun 2023 10:04:59 GMT"
								},
								{
									"key": "Content-Type",
									"value": "application/json"
								},
								{
									"key": "Transfer-Encoding",
									"value": "chunked"
								}
							],
							"cookie": [],
							"body": "{\n    \"codigo_promocional\": \"codigoTeste\",\n    \"email\": \"email\",\n    \"id\": 1,\n    \"nome\": \"Teste\",\n    \"role\": 0,\n    \"token\": \"eyJ0eXAiOiAiSldUIiwgImFsZyIgOiAiSFMyNTYifQ.eyJleHAiOiIxNjg3NDI4Mjk5IiwiaWF0IjoiMTY4NzQyODI5OSIsImlzcyI6Imdlc3R3aW4tcmVnaXN0b3MgYXBpIn0.MJiQnRAxsogoMaGulGI8zNC7ruQext_IikbC82RAkdU\"\n}"
						}
					]
				},
				{
					"name": "Logout",
					"event": [
						{
							"listen": "test",
							"script": {
								"exec": [
									"pm.collectionVariables.set('token', '');"
								],
								"type": "text/javascript"
							}
						}
					],
					"request": {
						"auth": {
							"type": "noauth"
						},
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"token\" : {{token}}\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": "{{endereco}}/api/auth/logout",
						"description": "Permite fazer o login para utilizar a maioria dos endpoints desta Api.  \n\nEste pedido devolve um token que deve ser incluido na maioria dos pedidos a esta Api."
					},
					"response": [
						{
							"name": "Login",
							"originalRequest": {
								"method": "POST",
								"header": [],
								"body": {
									"mode": "raw",
									"raw": "{\n    \"username\": \"teste\",\n    \"password\": \"teste\"\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": {
									"raw": "{{endereco}}/api/login",
									"host": [
										"{{endereco}}"
									],
									"path": [
										"api",
										"login"
									],
									"query": [
										{
											"key": "username",
											"value": "ola",
											"disabled": true
										},
										{
											"key": "password",
											"value": "joaquim",
											"disabled": true
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Date",
									"value": "Fri, 22 Jun 2023 10:04:59 GMT"
								},
								{
									"key": "Content-Type",
									"value": "application/json"
								},
								{
									"key": "Transfer-Encoding",
									"value": "chunked"
								}
							],
							"cookie": [],
							"body": "{\n    \"codigo_promocional\": \"codigoTeste\",\n    \"email\": \"email\",\n    \"id\": 1,\n    \"nome\": \"Teste\",\n    \"role\": 0,\n    \"token\": \"eyJ0eXAiOiAiSldUIiwgImFsZyIgOiAiSFMyNTYifQ.eyJleHAiOiIxNjg3NDI4Mjk5IiwiaWF0IjoiMTY4NzQyODI5OSIsImlzcyI6Imdlc3R3aW4tcmVnaXN0b3MgYXBpIn0.MJiQnRAxsogoMaGulGI8zNC7ruQext_IikbC82RAkdU\"\n}"
						}
					]
				}
			]
		},
		{
			"name": "Pais Copy",
			"item": [
				{
					"name": "GetPais",
					"request": {
						"method": "GET",
						"header": [],
						"url": {
							"raw": "{{endereco}}/api/paises",
							"host": [
								"{{endereco}}"
							],
							"path": [
								"api",
								"paises"
							],
							"query": [
								{
									"key": "alpha2",
									"value": "",
									"disabled": true
								},
								{
									"key": "alpha3",
									"value": "",
									"disabled": true
								},
								{
									"key": "ativo",
									"value": "",
									"disabled": true
								},
								{
									"key": "nome",
									"value": "",
									"disabled": true
								},
								{
									"key": "id",
									"value": null,
									"disabled": true
								},
								{
									"key": "vies",
									"value": null,
									"disabled": true
								}
							]
						},
						"description": "Permite obter os paises onde é vendido o gestwin.\n\nPode ser feita pesquisa por alpha2, alpha3, nome,ativo, vies ou id."
					},
					"response": [
						{
							"name": "GetPais",
							"originalRequest": {
								"method": "GET",
								"header": [],
								"url": {
									"raw": "{{endereco}}/api/paises",
									"host": [
										"{{endereco}}"
									],
									"path": [
										"api",
										"paises"
									],
									"query": [
										{
											"key": "alpha2",
											"value": "",
											"disabled": true
										},
										{
											"key": "alpha3",
											"value": "",
											"disabled": true
										},
										{
											"key": "ativo",
											"value": "",
											"disabled": true
										},
										{
											"key": "nome",
											"value": "",
											"disabled": true
										},
										{
											"key": "id",
											"value": null,
											"disabled": true
										},
										{
											"key": "vies",
											"value": null,
											"disabled": true
										}
									]
								}
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Date",
									"value": "Fri, 22 Jun 2023 10:08:11 GMT"
								},
								{
									"key": "Content-Type",
									"value": "application/json"
								},
								{
									"key": "Transfer-Encoding",
									"value": "chunked"
								}
							],
							"cookie": [],
							"body": "[\n    {\n        \"alpha2\": \"PT\",\n        \"alpha3\": \"PRT\",\n        \"ativo\": true,\n        \"id\": 1,\n        \"is_vies\": true,\n        \"nome\": \"Portugal\"\n    },\n    {\n        \"alpha2\": \"MZ\",\n        \"alpha3\": \"MOZ\",\n        \"ativo\": true,\n        \"id\": 2,\n        \"is_vies\": false,\n        \"nome\": \"Moçambique\"\n    },\n    {\n        \"alpha2\": \"CV\",\n        \"alpha3\": \"CPV\",\n        \"ativo\": true,\n        \"id\": 3,\n        \"is_vies\": false,\n        \"nome\": \"Cabo Verde\"\n    },\n    {\n        \"alpha2\": \"ST\",\n        \"alpha3\": \"STP\",\n        \"ativo\": true,\n        \"id\": 4,\n        \"is_vies\": false,\n        \"nome\": \"São Tomé e Príncipe\"\n    },\n    {\n        \"alpha2\": \"AO\",\n        \"alpha3\": \"AGO\",\n        \"ativo\": true,\n        \"id\": 5,\n        \"is_vies\": false,\n        \"nome\": \"Angola\"\n    }\n]"
						}
					]
				},
				{
					"name": "PostCreatePais",
					"request": {
						"method": "POST",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"alpha2\":\"\",\n    \"alpha3\":\"\",\n    \"ativo\":true,\n    \"vies\":true,\n    \"nome\":\"\"\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": "{{endereco}}/api/paises",
						"description": "Permite criar um novo país"
					},
					"response": [
						{
							"name": "PostCreatePais",
							"originalRequest": {
								"method": "POST",
								"header": [],
								"body": {
									"mode": "raw",
									"raw": "{\n    \"alpha2\":\"\",\n    \"alpha3\":\"\",\n    \"ativo\":true,\n    \"vies\":true,\n    \"nome\":\"\"\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": "{{endereco}}/api/paises"
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Date",
									"value": "Fri, 22 Jun 2023 10:08:21 GMT"
								},
								{
									"key": "Content-Type",
									"value": "application/json"
								},
								{
									"key": "Transfer-Encoding",
									"value": "chunked"
								}
							],
							"cookie": [],
							"body": "{\n    \"alpha2\": \"\",\n    \"alpha3\": \"\",\n    \"ativo\": true,\n    \"is_vies\": true,\n    \"nome\": \"\"\n}"
						}
					]
				},
				{
					"name": "UpdatePais",
					"request": {
						"method": "PUT",
						"header": [],
						"body": {
							"mode": "raw",
							"raw": "{\n    \"alpha2\":\"\",\n    \"alpha3\":\"\",\n    \"ativo\":true,\n    \"vies\":true,\n    \"nome\":\"\",\n    \"id\":6\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": "{{endereco}}/api/paises",
						"description": "Permite editar um país.\n\nA pesquisa do país a editar é feita através do id."
					},
					"response": [
						{
							"name": "UpdatePais",
							"originalRequest": {
								"method": "PUT",
								"header": [],
								"body": {
									"mode": "raw",
									"raw": "{\n    \"alpha2\":\"\",\n    \"alpha3\":\"\",\n    \"ativo\":true,\n    \"vies\":true,\n    \"nome\":\"\",\n    \"id\":6\n}",
									"options": {
										"raw": {
											"language": "json"
										}
									}
								},
								"url": "{{endereco}}/api/paises"
							},
							"status": "OK",
							"code": 200,
							"_postman_previewlanguage": "json",
							"header": [
								{
									"key": "Date",
									"value": "Fri, 22 Jun 2023 10:08:47 GMT"
								},
								{
									"key": "Content-Type",
									"value": "application/json"
								},
								{
									"key": "Transfer-Encoding",
									"value": "chunked"
								}
							],
							"cookie": [],
							"body": "{\n    \"alpha2\": \"\",\n    \"alpha3\": \"\",\n    \"ativo\": true,\n    \"is_vies\": true,\n    \"nome\": \"\"\n}"
						}
					]
				}
			]
		}
	]
}
```

**Comment by jonrosner** [comment] 2024-08-02 19:42
I pushed a fix for the collection you posted. Can you try it with your full collection? Unfortunately the Postman JSON export has a lot of edge cases...

**Closed** 2024-08-05 08:53 UTC

**Comment by Drilio** [comment] 2024-08-07 07:59
Same here it works, thank you !
